### ISSUE TITLE
你好，能否发一下比赛数据，万分感谢！

### ISSUE THREAD

**Issue by godzzbboss** [whoami-zy/fault-forecast#1]
邮箱1027785756@qq.com

**Comment by whoami-zy** [comment]
这个，数据在我家里面的电脑，我现在还在外地出差。这个数据也挺大的。在交流群里面问问 有没有存网盘的
------------------ 原始邮件 ------------------
发件人: "godzzbboss"<notifications@github.com>;
发送时间: 2019年6月20日(星期四) 上午10:45
收件人: "whoami-zy/fault-forecast"<fault-forecast@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [whoami-zy/fault-forecast] 你好，能否发一下比赛数据，万分感谢！ (#1)




邮箱1027785756@qq.com

**Comment by godzzbboss** [comment]
好的，谢谢

**Comment by TangDuoBuTiao** [comment]
同求数据，谢谢大佬！邮箱：296206234@qq.com
